/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TemplateVersion {
    }
}
declare global {
    interface HTMLTemplateVersionElement extends Components.TemplateVersion, HTMLStencilElement {
    }
    var HTMLTemplateVersionElement: {
        prototype: HTMLTemplateVersionElement;
        new (): HTMLTemplateVersionElement;
    };
    interface HTMLElementTagNameMap {
        "template-version": HTMLTemplateVersionElement;
    }
}
declare namespace LocalJSX {
    interface TemplateVersion {
    }
    interface IntrinsicElements {
        "template-version": TemplateVersion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "template-version": LocalJSX.TemplateVersion & JSXBase.HTMLAttributes<HTMLTemplateVersionElement>;
        }
    }
}
